### ISSUE TITLE
config options are discarded if invoked as root

### ISSUE THREAD

**Issue by crpb** [grommunio/gromox#101]
Hi,

it seems if i use e.g. `/usr/libexec/gromox/imap -c /etc/gromox/z_archiver/imap.cfg` as user root the service will be restarted as user gromox but then doesn't use that config directive anymore.
Didn't try any other service but i guess that could apply to any service and not just imap.

[full story](https://community.grommunio.com/d/1710-imap-nopass-not-working-anymore/11)

**Comment by jengelh** [comment]
gromox-2.30-20-gaef56e412
