### ISSUE TITLE
segfault when sending mail via EWS

### ISSUE THREAD

**Issue by amaccuish** [grommunio/gromox#102]
Jul 16 21:26:54 mx01 kernel: traps: ep_pool/0[17747] general protection fault ip:7f1093fd7a47 sp:7f10467baee0 error:0 in libgxh_ews.so.0.0.0[7f1093f27000+11a000]
Jul 16 21:26:54 mx01 systemd[1]: Started Process Core Dump (PID 17968/UID 0).
Jul 16 21:26:57 mx01 systemd-coredump[17969]: [🡕] Process 17677 (http) of user 493 dumped core.

Any way I can privately share the dump if needed.

[stack_trace.txt](https://github.com/user-attachments/files/16255721/stack_trace.txt)

gromox-http 2.30.38.g713d40b

**Comment by jengelh** [comment]
```
tEmailAddressType::mkRecipient::
!       if(!EmailAddress)
                throw EWSError::InvalidRecipients(E3290);
```
```
EWSContext::toContent::
                TARRAY_SET* rcpts = content->children.prcpts;
                for(const auto& rcpt : *item.ToRecipients)
                        rcpt.mkRecipient(rcpts->emplace(), MAPI_TO);
                for(const auto& rcpt : *item.CcRecipients)
!                       rcpt.mkRecipient(rcpts->emplace(), MAPI_CC);
                for(const auto& rcpt : *item.BccRecipients)
                        rcpt.mkRecipient(rcpts->emplace(), MAPI_BCC);
```

**Comment by amaccuish** [comment]
So I am using Evolution and just entering normal email addresses in like usual. Both in the format "XXX XXX <xxx@xxx.xxx>, " and "xxx@xxx.xxx".

Also maybe this user is facing the same issue? https://community.grommunio.com/d/1734-gromox-http-segfault-when-trying-to-send-e-mail-from-macos-mailapp

**Comment by malignus** [comment]
Did a check on different MacOS versions (MacOS is 12.7.5 Monterey and MacOS 14.5 Sonoma) as well as default mail.app the problem is the same even with the latest version of gromox (gromox-2.30.55.g517d5c2-34.1)

`http[7677]: /usr/include/c++/11/optional:439: constexpr _Tp& std::_Optional_base_impl<_Tp, _Dp>::_M_get() [with _Tp = gromox::EWS::Structures::sFolderSpec; _Dp = std::_Optional_base<gromox::EWS::Structures::sFolderSpec, false, false>]: Assertion 'this->_M_is_engaged()' failed.`

**Comment by jengelh** [comment]
There is just a single `optional<sFolderSpec>` in the source code, so that is probably where. But that would be a secondary issue then.

**Comment by juliaschroeder** [comment]
I would guess that `item.CCRecipients` (`std::opional<std::vector<tEmailAddressType>>`) is empty.  
The for loop accesses the uninitialized value (`std::vector`) and iterates it, yielding a garbage reference (`rcpt`), leading to a segfault when first accessing it (member `EmailAddress` in `tEmailAddressType::mkRecipient`).

**Comment by jengelh** [comment]
20c36cca962074d12a1b6a0815ae3c520206194e

**Comment by malignus** [comment]
will test once an updated package is available. thank you so far

**Comment by malignus** [comment]
Hi,
updated to the latest version, problem still exists...
`http[81407]: /usr/include/c++/11/optional:439: constexpr _Tp& std::_Optional_base_impl<_Tp, _Dp>::_M_get() [with _Tp = gromox::EWS::Structures::sFolderSpec; _Dp = std::_Optional_base<gromox::EWS::Structures::sFolderSpec, false, false>]: Assertion 'this->_M_is_engaged()' failed.`

**Comment by malignus** [comment]
can provide a coredump with debug information

**Comment by jengelh** [comment]
Sure. You can send links to me privately if there is concern about data being exposed by coredumps.

**Comment by malignus** [comment]
[coredump](https://github.com/user-attachments/files/16438158/coredump.tar.gz)
[stacktrace](https://github.com/user-attachments/files/16438239/stacktrace.txt)

**Comment by malignus** [comment]
for further debugging I captured the request that leads to the coredump

```
http[119557]: << 12:34:51.505739 [::ffff:127.0.0.1]:44472->[::ffff:127.0.0.1]:10443 417 bytes
http[119557]: POST /EWS/Exchange.asmx HTTP/1.1
http[119557]: Host: [RETRACTED]
http[119557]: X-Real-IP: [RETRACTED]
http[119557]: X-Forwarded-For: [RETRACTED]
http[119557]: Connection: Keep-Alive
http[119557]: Content-Length: 1812
http[119557]: accept: */*
http[119557]: content-type: text/xml; charset=utf-8
http[119557]: accept-language: de-DE,de;q=0.9
http[119557]: accept-encoding: gzip, deflate, br
http[119557]: user-agent: AppleExchangeWebServices/818.120.2 Mail/3696.120.41.1.8
http[119557]: authorization: Basic [RETRACTED]
http[119557]:
http[119557]: <<-EOH
gromox-http[119557]: rhost=[::ffff:127.0.0.1]:44472 user=[RETRACTED] htp_auth success
http[119557]: << 12:34:51.511212 [::ffff:127.0.0.1]:44472->[::ffff:127.0.0.1]:10443 1812 bytes
http[119557]: <?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><soap:Header><t:RequestServerVersion Version="Exchange2007_SP1"/></soap:Header><soap:Body><m:CreateItem MessageDisposition="SendOnly" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><m:Items><t:Message><t:MimeContent>[RETRACTED]</t:MimeContent><t:Importance>Normal</t:Importance><t:ExtendedProperty><t:ExtendedFieldURI PropertyName="MessageNotJunkFlag" PropertySetId="A7B529B5-4B75-47A7-A24F-20743D6C55CD" PropertyType="Boolean"/><t:Value>true</t:Value></t:ExtendedProperty><t:ExtendedProperty><t:ExtendedFieldURI PropertyTag="0xe07" PropertyType="Integer"/><t:Value>1</t:Value></t:ExtendedProperty><t:ExtendedProperty><t:ExtendedFieldURI PropertyTag="0x1090" PropertyType="Integer"/><t:Value>0</t:Value></t:ExtendedProperty><t:ToRecipients><t:Mailbox><t:Name>[RETRACTED]</t:Name><t:EmailAddress>[RETRACTED]</t:EmailAddress></t:Mailbox></t:ToRecipients><t:From><t:Mailbox><t:Name>[RETRACTED]</t:Name><t:EmailAddress>[RETRACTED]</t:EmailAddress></t:Mailbox></t:From></t:Message></m:Items></m:CreateItem></soap:Body></soap:Envelope>
http[119557]: <<-EOB
http[119557]: /usr/include/c++/11/optional:439: constexpr _Tp& std::_Optional_base_impl<_Tp, _Dp>::_M_get() [with _Tp = gromox::EWS::Structures::sFolderSpec; _Dp = std::_Optional_base<gromox::EWS::Structures::sFolderSpec, false, false>]: Assertion 'this->_M_is_engaged()' failed.
```

**Comment by jengelh** [comment]
f1d7ee1609f27db719b61c3a9a2e4a0c2434b301
