### ISSUE TITLE
e2ghelper not documented

### ISSUE THREAD

**Issue by crpb** [grommunio/gromox#103]
Hi,

is there a reason there isn't any documentation(man) for gromox-e2ghelper?
I guess it could at least be listed in gromox(7) as a wrapper for `gromox-pff2mt ... | gromox-mt2exm ..` from what i [understand](https://github.com/grommunio/gromox/blob/e7685ddd00fb99be0651852917d1ba40a4e4d399/tools/e2ghelper.cpp#L50-L63) or not?

~cb

**Comment by jengelh** [comment]
gromox-2.32-5-ga74309e7c
