### ISSUE TITLE
headers vanish on move

### ISSUE THREAD

**Issue by crpb** [grommunio/gromox#107]
Hey,

it seems that part of the headers in a mail vanish when i move a mail from one folder to another.
This was done in /web and i could still see the information via outlook and /web but not in imap anymore where i still would like them to see.

This might also explain why there are constantly duplicates in the archive as it couldn't match the mails when archiving is done with a always_bcc mailbox and each mailbox on it's own for sorting into folders.

edit: i just double checked in subfolders and picked randomly.. very short in comparison to the INBOX mails.
and it also happens with mails that are automatically moved by inbox rules

regards,
Christopher

**Comment by jengelh** [comment]
Just a heads-up. I started tinkering on this, but it is not complete yet. https://github.com/jengelh/gromox/commits/gxh-107/

**Comment by jengelh** [comment]
gromox-2.37-12-g73d941d05

**Comment by jengelh** [comment]
gromox-2.46-97-g 77faca46f

**Comment by Oroo9CeL** [comment]
Thanks for the fix!
Now the headers are not removed in IMAP/Thunderbird when you move an email to another folder in Outlook or webmail.
But:
When the midb is rebuilt and the account is resynchronized, I don't have a Received header in Thunderbird for any emails. I think this is related to this bug report.

The following procedure reproduces the issue:
On the client:
- Exit Thunderbird
- Delete Thunderbird ~/.thunderbird/xxx/ImapMail/*
On the server:
- systemctl stop gromox-midb
- systemctl stop gromox-imap
- Delete /var/lib/gromox/user/domain/username/exmdb/midb*
- Empty /var/lib/gromox/user/domain/username/eml/*
- Empty /var/lib/gromox/user/domain/username/ext/*
- gromox-mkmidb username
- systemctl start gromox-midb
- systemctl start gromox-imap
On the client:
- Start Thunderbird and wait until the files and DB have been rebuilt
- View the source code of any email. No received headers available.
- The received headers for this email are available in WebUI or Outlook.

Thank you!

**Comment by Oroo9CeL** [comment]
@jengelh 
Please reopen the bug report so that it is not forgotten.

Kind regards

**Comment by jengelh** [comment]
One ticket, one issue. No overloading.
