### ISSUE TITLE
Folders via IMAP not working with German umlauts or ampersand in folder name

### ISSUE THREAD

**Issue by dfied** [grommunio/gromox#115]
Client: current Thunderbird version 128.5.0
Gromox: gromox-2.38.5.g9866cfd-6.1
Rocky Linux 9.5 with current updates

Since some days I have problems using folders in gromox-imap that have german umlauts in its folder names. Also folders with ampersand are affected. 
I thought this was caused by #114 but the fix only stopped the sqlite error in the midb logs but the folders are still not accessible. The folders are greyed out in Thunderbird. When opening the subscribe dialog for folders, those folder are shown twice.
Also affected are the Trash folder (Gelöschte Objekte in German) and Drafts (Entwürfe).
Grommunio Web and Grommunio Sync are working as expected.

How can I help to analyze this problem?

bye
Daniel

**Comment by crpb** [comment]
Haha, yeah it doesn't like that at all :P.
```
[2024-12-11 21:30:30] IMAP> 3714 UID FETCH 1:* (FLAGS UID) 
[2024-12-11 21:30:30] IMAP< [FETCH data - 687 bytes]
[2024-12-11 21:30:46] IMAP> 3715 LIST "" "Deleted Items/&APw-l&AOQ-n&APYA3w-e" 
[2024-12-11 21:30:46] IMAP< 3715 OK LIST completed 
[2024-12-11 21:30:46] IMAP> 3716 CREATE "Deleted Items/&APw-l&AOQ-n&APYA3w-e" 
[2024-12-11 21:30:46] IMAP< 3716 NO server internal error, midb: cu_create_folder failed 
** IMAP error on gromi.xxxx.de: CREATE error
** can't create mailbox
[2024-12-11 21:31:26] IMAP> 4491 NOOP 
```
Also tested with other folders than trash. Claws-Mail here.

**Comment by crpb** [comment]
I just ran "search for new folders" on every mailbox and this fixed as it seems the usage of "Gelöschte Objekte" as i now can use the "emtpty" function.
Odd thing is that one of the mailboxes appears to be now english even tho it is displayed with de_DE in `exmdb store get` and another mailbox is shown as german like it used to.
Furthermore i can't seem to create/delete any folder with claws-mail. With alpine it worked tho .. 🙈

**Comment by jengelh** [comment]
gromox-2.38-11-gcf5168e65
gromox-2.38-13-gc8c7ff15b

**Comment by jengelh** [comment]
>Odd thing is that one of the mailboxes appears to be now english

claws does not know RFC 6154, and always (re-)creates folders called _Trash_, _Drafts_, _Queue_ even if you already have _Gelöschte Elemente_, _Entwürfe_, etc.

**Comment by crpb** [comment]
> _Trash_, _Drafts_, _Queue_ even if you already have _Gelöschte Elemente_, _Entwürfe_, etc.

yeah, but i also have the same english view in the webapp so that wasn't only in claws :P.

> gromox-2.38-14-g330426e88
works for me 👍🏼

**Comment by dfied** [comment]
works for me, too!
Thanks for the quick fix!
