### ISSUE TITLE
Extra line in addresses breaks DAV

### ISSUE THREAD

**Issue by amaccuish** [grommunio/gromox#120]
If a contact is edited in grommunio-web, and an address stored such as:

Beispielstr. 1
<empty line>
10374 Berlin

Then sabredav returns 500 as it can't produce a valid vcf.

> HTTP/1.1 500 Internal Server Error
> X-GDAV-Version: 1.3.74.94260cb
> X-Sabre-Version: 4.4.0
> Content-Type: application/xml; charset=utf-8
> 
> <?xml version="1.0" encoding="utf-8"?>
> <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
>   <s:sabredav-version>4.4.0</s:sabredav-version>
>   <s:exception>Sabre\VObject\ParseException</s:exception>
>   <s:message>Invalid Mimedir file. Line starting at 14 did not follow iCalendar/vCard conventions</s:message>
> </d:error>

**Comment by jengelh** [comment]
gromox-2.38-45-g524310c50
