### ISSUE TITLE
gromox/lib/dbop_mysql.cpp:53 - Admin Role name allowing for only 32 characters

### ISSUE THREAD

**Issue by MrPikPik** [grommunio/gromox#20]
When creating domains through the admin web interface and checking "Create domain admin role", a database error occurs if the domain name is longer than 17 characters since the generated role name results in "`Domain Admin ({DomainName})`".

We tracked the issue down to line 53 in `gromox/lib/dbop_mysql.cpp` where the admin roles table gets initially created. There the name field is set to be 32 characters long. There were no "patches" found in the table upgrades at the bottom of the file.

We would advise in allowing for longer names, 64 characters should suffice.

(Some other varchar-fields from other tables may need some overthinking too, but nothing struck us so far except maybe telephone numbers being only 20 characters while titles allowing for up to 128 characters)

**Comment by juliaschroeder** [comment]
We have looked into this issue and agreed that it would be more sensible to fix this in the admin-api for the following reasons:
- Raising the role name limit to 64 might solve the issue in your case, but not in general, as domain names can have up to 255 characters
- Role names should be short and descriptive and a 32 characters should really be sufficient

The auto-generation will thus be altered to produce a role name that fits into the length limit. Expect a fix in the coming days.

**Comment by StefanAkie** [comment]
This has been resolved via https://github.com/grommunio/admin-api/commit/c1f9802de4f95734cf5ba43e8892242ec2c4d775
