### ISSUE TITLE
Feature-Request: deldir

### ISSUE THREAD

**Issue by crpb** [grommunio/gromox#24]
Hey there,

with [delmsg](https://docs.grommunio.com/man/delmsg.8gx.html) i already can do tasks like for instance [empty all trashbins](https://github.com/crpb/grommunio/blob/main/env/.gromenv#L67-L126) (yes it could be improved, but for now it's working..).
But this wouldn't include deleted Folders in the Trashbin itself.
I did look a bit through the exchange.sqlite3 but with the references in there i wasn't so sure if should/could do a deletion with an sql-query and not break anything :see_no_evil: and also the Description in mind.
> This utility does not perform a “surgical” operation on the SQLite database directly, but connects to an exmdb server and issues the delete_messages RPC.

Are there any plans to add this functionality to **delmsg** or maybe another tool like e.g. **deldir**?

with many regards,
~crpb

**Comment by jengelh** [comment]
gromox-1.37-97-g09d54021d

**Comment by jengelh** [comment]
gromox-2.3-47-gb0d99f7c9
