### ISSUE TITLE
>2.5 unable to execute on Alpine

### ISSUE THREAD

**Issue by tiredofit** [grommunio/gromox#51]
I'm trying to compile and utilize gromox under Alpine Linux yet post `gromox-2.4` I am presented with the following error:

```
system: hostname is grommunio
system: SMTP server is [::1]:25
I can't work like this! iconv lacks support for the essential character set UTF-7. Perhaps you need to install some libc locale package.
```

Versions:
````
Alpine 3.16 
PHP 8.0 (distro package)
Libfmt (distro package)

GROMOX_VERSION=gromox-2.6
LIBHX_VERSION=v4.12
LIBHX_REPO_URL=https://codeberg.org/jengelh/libhx
LIBVMIME_VERSION=c6904bd7cf03f6cca92cf0d15aec02e7850e0276
GROMOX_REPO_URL=https://github.com/gromox/gromox
LIBVMIME_REPO_URL=https://github.com/kisli/vmime
````

I don't know what I am doing but a quick look seems that this may have been the start of it?
https://github.com/grommunio/gromox/commit/ff24702f4f76b5ae66a5947712cbdcaae4403a35

**Comment by jengelh** [comment]
Alpine uses musl libc, which does not have UTF-7 support.
```
$ echo hi world | iconv -f utf-8 -t utf-7
iconv: destination charset utf-7: Invalid argument
```
That's bad, because IMAP mandates UTF-7. I see that Alpine has gnu-libiconv-dev, a workaround is `./configure CPPFLAGS=-I/usr/include/gnu-iconv && make iconv_LIBS=-liconv`.

**Comment by tiredofit** [comment]
Thanks. Still no success. I tried using your guidance adding `gnu-libiconv-dev` in the build process and made the changes as advised (using instead: `CPPFLAGS=-I/usr/include/gnu-libiconv`).

My hackish way of checking to see if it was relying on the package involved uninstalling it and running zcore and see if it kicked up symbol errors, which it did. At a loss here on any further steps.

**Comment by jengelh** [comment]
bfb0fd4790d8e67e3fe99d97a1de0855d1b1006b

**Comment by tiredofit** [comment]
Many thanks! I'm in awe at your development skills.
