### ISSUE TITLE
Coredump in midb when connecting over IMAP

### ISSUE THREAD

**Issue by amaccuish** [grommunio/gromox#52]
See attached. Can also provide the actual dump separately if needed.
[dump.txt](https://github.com/grommunio/gromox/files/11183153/dump.txt)
[rpm.txt](https://github.com/grommunio/gromox/files/11183154/rpm.txt)

**Comment by amaccuish** [comment]
Version     : 2.7.115.acb779b
[dump.txt](https://github.com/grommunio/gromox/files/11183455/dump.txt)

**Comment by jengelh** [comment]
Ugh, this code is so fucking awful

**Comment by jengelh** [comment]
gromox-2.7-113-g2748d3dc2

**Comment by amaccuish** [comment]
That did it, thank you!
