### ISSUE TITLE
Mangled IMAP names

### ISSUE THREAD

**Issue by amaccuish** [grommunio/gromox#54]
Hi. I speak German, folder names since the last update are now mangled if they contain umlauts.

First screenshot is from Evolution, second from the Web UI:

![image](https://user-images.githubusercontent.com/9434795/233766501-dda31449-878b-46de-8bb1-4967cbb9e7ae.png)
![image](https://user-images.githubusercontent.com/9434795/233766510-969f63c0-9f50-4bb1-abad-5a876d1fdf2a.png)

**Comment by amaccuish** [comment]
![image](https://user-images.githubusercontent.com/9434795/233766567-d0103ea9-9bf9-478a-9e3c-17beea3ef79f.png)
I've also tried refreshing the folder list to fetch new names.

**Comment by amaccuish** [comment]
Thunderbird shows the same behaviour:
![image](https://user-images.githubusercontent.com/9434795/233766606-485eeb60-3f4f-4433-81d5-edf22bfe3cf4.png)

**Comment by jengelh** [comment]
(EWS is the awful one because of all the XML.)
Anyway, so then Thunderbird also has problems with e.g. Dovecot?

Dovecot:
```
$ telnet :: 144
Trying ::...
Connected to ::.
Escape character is '^]'.
* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS AUTH=PLAIN AUTH=LOGIN] Dovecot ready.
a login a b
a OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SNIPPET=FUZZY PREVIEW=FUZZY PREVIEW STATUS=SIZE SAVEDATE LITERAL+ NOTIFY SPECIAL-USE] Logged in
a list "" %
* LIST (\NoInferiors) "/" "Gel&APY-schte Elemente"
* LIST (\NoInferiors) "/" Gel&APY-scht
* LIST (\NoInferiors) "/" Foo
* LIST (\HasNoChildren) "/" INBOX
a OK List completed (0.001 + 0.000 secs).
```

gromox-imap:
```
$ telnet :: 143
Trying ::...
Connected to ::.
Escape character is '^]'.
* OK [CAPABILITY IMAP4rev1 XLIST SPECIAL-USE UNSELECT UIDPLUS IDLE AUTH=LOGIN] Service ready
a login aa b
a OK logged in
a list "" %
* LIST (\HasChildren) "/" "INBOX"
* LIST (\HasNoChildren) "/" "Entw&APw-rfe"
* LIST (\HasNoChildren) "/" "Gesendete Elemente"
* LIST (\HasNoChildren) "/" "Gel&APY-schte Elemente"
* LIST (\HasNoChildren) "/" "Junk-E-Mail"
* LIST (\HasNoChildren) "/" "Archive"
* LIST (\HasNoChildren) "/" "Conversation History"
* LIST (\HasNoChildren) "/" "OS|ECM-Archiv"
* LIST (\HasNoChildren) "/" "OS|ECM-Autoarchiv"
* LIST (\HasNoChildren) "/" "RSS Feeds"
* LIST (\HasNoChildren) "/" "Trash"
a OK LIST completed
```

**Comment by amaccuish** [comment]
Hmm no. We actually moved from Dovecot using imap-sync. The folder name was displayed with Dovecot correctly and up until last week also by gromox-imap.

**Comment by jengelh** [comment]
gromox-2.8-76-ge5fd1df5b
