### ISSUE TITLE
IMAP stops working after some time

### ISSUE THREAD

**Issue by amaccuish** [grommunio/gromox#55]
Since the recent IMAP rework, I have the issue that my IMAP clients stop displaying any messages after a while. It appears as if I have an empty inbox.

![image](https://user-images.githubusercontent.com/9434795/236664820-8d6b3949-4d1b-4d31-aea5-e95301cd918b.png)

In the logs for gromox-imap, I can see. Let me know if anything else is needed. I couldn't find a relevant config setting that could increase this limit. A restart of gromox-imap fixes the issue temporarily.

> E-1995: XARRAY pool exhausted

**Comment by jengelh** [comment]
gromox-2.8-97-g9dcd0b1fa
