### ISSUE TITLE
Support for DNSBL/API lookup before authentication?

### ISSUE THREAD

**Issue by robert-scheck** [grommunio/gromox#58]
Maybe I'm overlooking an existing feature that could be leveraged, but do you see a chance to add a DNSBL/API lookup before (especially for POP3, IMAP) authentication that (protocol-aware) rejects or continues the connection request depending on the lookup result?

Background: [Spamhaus](https://www.spamhaus.com/dataset/ip-blocklists/) and [Abusix](https://abusix.com/resources/blocklists/abusix-mail-intelligence-authentication-ip-list/) provide so-called "AuthBL", intended to reduce abuse of brute-force or stolen/leaked credentials for SMTP relaying. While it's relatively easy to configure AuthBL for Postfix (e.g. `smtpd_delay_reject = no`, `smtpd_helo_restrictions = reject_rbl_client=<apikey>.authbl.dq.spamhaus.net=127.0.0.20`, `smtpd_helo_required = yes` on MTAs servers offering SMTP relaying to end users), I would like to extend the scope from SMTP to protocols that actually allow accessing the mailbox, such as POP3 and IMAP. The default recommendation by both vendors is to just forbid relaying using AuthBL (after successful authentication), but not to forbid the login itself already (thus an attacker knows that the credentials are valid and might simply proceed to grab the mailbox data). For HTTP(S) there might be standard solutions directly inside NGINX (maybe [ngx_http_auth_request_module](https://nginx.org/en/docs/http/ngx_http_auth_request_module.html), I didn't check in-depth whether it fits the API). For Abusix, I didn't find an API for AuthBL, just the "[Getting Started](https://docs.abusix.com/abusix-mail-intelligence/gbG8EcJ3x3fSUv8cMZLiwA/setting-up-different-systems/dmw9dcwSGSNQiLTssFAnBW)", Spamhaus provides [DNS](https://docs.spamhaus.com/datasets/docs/source/10-data-type-documentation/datasets/040-zones.html) and [API](https://docs.spamhaus.com/datasets/docs/source/70-access-methods/web-query-service/040-api-queries.html) lookups for AuthBL.

If you don't think this request adds much value to gromox, feel free to close simply (the idea originates from cases that fail2ban does not catch due to its nature).

**Comment by jengelh** [comment]
gromox-2.9-61-g09f71ba0a for an initial implementation
