### ISSUE TITLE
typo: gromox-mkmidb --help

### ISSUE THREAD

**Issue by crpb** [grommunio/gromox#59]
Hi,

shouldn't it say **midb.sqlite3**?

https://github.com/grommunio/gromox/blob/35f89ab9e2eaf16a4ddadf3260b576f779c732c9/tools/mkmidb.cpp#LL41C85-L41C85

https://github.com/grommunio/gromox/blame/35f89ab9e2eaf16a4ddadf3260b576f779c732c9/tools/mkmidb.cpp#L41

**Comment by jengelh** [comment]
gromox-2.9-30-g9d3b8b063
