### ISSUE TITLE
gromox-snapshot probably doesn't need root privileges

### ISSUE THREAD

**Issue by wfrisch** [grommunio/gromox#61]
In gromox-snapshot, the function `static int do_purge()` uses `btrfs subvolume delete` to purge old snapshots. This operation requires root, which is why the systemd service has been changed from running with lesser privileges (gromox:gromox) to (root:root). However this may not be necessary,  thanks to a new-ish btrfs feature introduced with Linux 4.18:

Quote from the btrfs(5) man page:

> Historically, any user could create a snapshot even if he was not owner
> of the source subvolume, the subvolume deletion has been restricted for
> that reason. The subvolume creation has been restricted but this mount
> option is still required. This is a usability issue. Since 4.18, the
> rmdir(2) syscall can delete an empty subvolume just like an ordinary
> directory. Whether this is possible can be detected at runtime, see
> rmdir_subvol feature in FILESYSTEM FEATURES.

It should be sufficient to simply delete the snapshot directory recursively, as long as we have kernel 4.18+. In order to maintain backwards compatibility with older distros, the presence of this feature could be queried with an existence test of `/sys/fs/btrfs/features/rmdir_subvol`, and if it's absent, run the old code path that requires root.

**Comment by jengelh** [comment]
>existence test of /sys/fs/btrfs/features/rmdir_subvol, and if it's absent, run the old code path that requires root

rmdir_subvol has shortcomings:

* It could be argued that rm is less efficient, since it issues a lot of syscalls (individual file deletion as far as the kernel is concerned)
* It is possible to create snapshots you cannot delete afterwards if there are some directories to which the deletor has no permissions.

```
10:04 f3:/mnt # cat /sys/fs/btrfs/features/rmdir_subvol
0
10:04 f3:/mnt # uname -a
Linux f3 6.3.9-1-default #1 SMP PREEMPT_DYNAMIC Thu Jun 22 03:53:43 UTC 2023 (0df701d) x86_64 x86_64 x86_64 GNU/Linux (Tumbleweed)

mnt$ ls -Ral
.:
total 8
drwxr-xr-x  1 jengelh root   4 Jun 30 10:06 .
drwxr-xr-x 17 root    root 232 Jun 14 22:55 ..
drwxr-xr-x  1 jengelh root   6 Jun 30 10:06 1

./1:
total 16
drwxr-xr-x 1 jengelh root  6 Jun 30 10:06 .
drwxr-xr-x 1 jengelh root  4 Jun 30 10:06 ..
drwxr-xr-x 1 root    root 12 Jun 30 10:06 etc

./1/etc:
total 4
drwxr-xr-x 1 root    root 12 Jun 30 10:06 .
drwxr-xr-x 1 jengelh root  6 Jun 30 10:06 ..
-rw-r--r-- 1 root    root  6 Jun 30 10:06 passwd

mnt$ btrfs sub snap 1 2
Create a snapshot of '1' in './2'
mnt $ btrfs sub del 2
WARNING: cannot read default subvolume id: Operation not permitted
Delete subvolume (no-commit): '/mnt/2'
ERROR: Could not destroy subvolume/snapshot: Operation not permitted
WARNING: deletion failed with EPERM, you don't have permissions or send may be in progress
10:07 f3:/mnt $ rmdir 2
rmdir: failed to remove '2': Directory not empty
mnt $ rm -Rf 2
rm: cannot remove '2/etc/passwd': Permission denied
```

**Comment by jengelh** [comment]
User-based rm with drawbacks.
