### ISSUE TITLE
Long-running RPCs mistrigger timeout logic

### ISSUE THREAD

**Issue by jengelh** [grommunio/gromox#64]
Version: gromox-2.10

```
# /usr/sbin/gromox-mbop -u @somedomain.de vacuum
vacuum: the operation failed
```

Do something about clients misinterpreting long-running RPCs.

**Comment by jengelh** [comment]
gromox-2.10-92-ga49a14a3b

**Comment by crpb** [comment]
gromox-2.10.117.06d0808-lp155.100.2.x86_64

still failing :shrug:

**Comment by jengelh** [comment]
But not because of exmdb_client, but
```
                if (!pdb->giant_lock.try_lock_for(DB_LOCK_TIMEOUT)) {
```
