### ISSUE TITLE
Error in compilation

### ISSUE THREAD

**Issue by gilbertoferreira** [grommunio/gromox#65]
Hi there

I am trying to compile gromox in Debian 12 and Ubuntu 22.04 and in both system get this error:
```
lib/email/send.cpp:61:27: error: no matching function for call to 'vmime::net::transport::send(vmime::mailbox&, vmime::mailboxList&, vmime::utility::inputStreamStringAdapter&, std::__cxx11::basic_string<char>::size_type, std::nullptr_t, <brace-enclosed initializer list>, <brace-enclosed initializer list>)'
   61 |                 xprt->send(vsender, vrcpt_list, ct_adap, content.size(), nullptr, {}, {});
      |                 ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from lib/email/send.cpp:9:
/usr/include/vmime/net/transport.hpp:70:22: note: candidate: 'virtual void vmime::net::transport::send(std::shared_ptr<vmime::message>, vmime::utility::progressListener*)'
   70 |         virtual void send(shared_ptr <vmime::message> msg, utility::progressListener* progress = NULL);
      |                      ^~~~
/usr/include/vmime/net/transport.hpp:70:22: note:   candidate expects 2 arguments, 7 provided
/usr/include/vmime/net/transport.hpp:81:22: note: candidate: 'virtual void vmime::net::transport::send(const vmime::mailbox&, const vmime::mailboxList&, vmime::utility::inputStream&, vmime::size_t, vmime::utility::progressListener*, const vmime::mailbox&)'
   81 |         virtual void send
      |                      ^~~~
/usr/include/vmime/net/transport.hpp:81:22: note:   candidate expects 6 arguments, 7 provided
/usr/include/vmime/net/transport.hpp:99:22: note: candidate: 'virtual void vmime::net::transport::send(std::shared_ptr<vmime::message>, const vmime::mailbox&, const vmime::mailboxList&, vmime::utility::progressListener*, const vmime::mailbox&)'
   99 |         virtual void send
      |                      ^~~~
/usr/include/vmime/net/transport.hpp:99:22: note:   candidate expects 5 arguments, 7 provided
make[1]: *** [Makefile:4043: lib/email/libgromox_email_la-send.lo] Error 1
make[1]: Leaving directory '/root/gromox-2.10'
make: *** [Makefile:2156: all] Error 2
```

How can I fix it?

Thanks

**Comment by gilbertoferreira** [comment]
Just an update
I tried with the vmime git repo and still get a bunch of errors:

/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::text::getWordAt(unsigned long)'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::streamContentHandler::isEncoded() const'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::text::decodeAndUnfold(vmime::parsingContext const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, vmime::text*)'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::utility::encoder::encoderFactory::create(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: ./.libs/libgromox_common.so: undefined reference to `vmime::text::~text()'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::streamContentHandler::~streamContentHandler()'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::text::isEmpty() const'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vtable for vmime::utility::filteredInputStream'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::streamContentHandler::streamContentHandler(std::shared_ptr<vmime::utility::inputStream> const&, unsigned long, vmime::encoding const&)'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::streamContentHandler::extract(vmime::utility::outputStream&, vmime::utility::progressListener*) const'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::security::sasl::builtinSASLMechanism::builtinSASLMechanism(std::shared_ptr<vmime::security::sasl::SASLContext> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::text::text(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, vmime::charset const&)'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::utility::datetimeUtils::toUniversalTime(vmime::datetime const&)'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::streamContentHandler::isBuffered() const'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `typeinfo for vmime::streamContentHandler'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::utility::datetimeUtils::getWeekOfYear(int, int, int, bool)'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vtable for vmime::utility::filteredOutputStream'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::security::sasl::defaultSASLAuthenticator::defaultSASLAuthenticator()'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::utility::filteredOutputStream::getBlockSize()'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::text::getWordAt(unsigned long) const'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::streamContentHandler::streamContentHandler()'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::streamContentHandler::getLength() const'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::text::getWholeBuffer[abi:cxx11]() const'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::utility::datetimeUtils::getDayOfWeek(int, int, int)'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::text::text(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: ./.libs/libgromox_common.so: undefined reference to `vmime::text::getConvertedText[abi:cxx11](vmime::charset const&, vmime::charsetConverterOptions const&) const'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `typeinfo for vmime::utility::filteredOutputStream'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::streamContentHandler::extractRaw(vmime::utility::outputStream&, vmime::utility::progressListener*) const'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::streamContentHandler::getEncoding() const'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::text::getWordCount() const'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::streamContentHandler::setContentTypeHint(vmime::mediaType const&)'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::utility::encoder::qpEncoder::qpEncoder()'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::utility::inputStreamByteBufferAdapter::inputStreamByteBufferAdapter(unsigned char const*, unsigned long)'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::utility::encoder::qpEncoder::RFC2047_getEncodedLength(unsigned char)'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::text::text(vmime::word const&)'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::text::removeAllWords()'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::text::operator==(vmime::text const&) const'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::streamContentHandler::generate(vmime::utility::outputStream&, vmime::encoding const&, unsigned long) const'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vtable for vmime::utility::dotFilteredOutputStream'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vtable for vmime::utility::inputStreamByteBufferAdapter'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::text::decodeAndUnfold(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, vmime::text*)'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vtable for vmime::utility::CRLFToLFFilteredOutputStream'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::text::operator=(vmime::text const&)'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::utility::encoder::encoderFactory::getInstance()'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::utility::dotFilteredInputStream::dotFilteredInputStream(vmime::utility::inputStream&)'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::utility::dotFilteredOutputStream::dotFilteredOutputStream(vmime::utility::outputStream&)'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::utility::encoder::b64Encoder::b64Encoder()'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::text::text()'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::streamContentHandler::getContentTypeHint() const'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::textPartFactory::create(vmime::mediaType const&)'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::utility::dotFilteredOutputStream::flush()'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::utility::encoder::encoder::getProperties()'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::text::encodeAndFold(vmime::generationContext const&, vmime::utility::outputStream&, unsigned long, unsigned long*, int) const'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::text::appendWord(std::shared_ptr<vmime::word> const&)'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::utility::filteredInputStream::getBlockSize()'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::streamContentHandler::setData(std::shared_ptr<vmime::utility::inputStream> const&, unsigned long, vmime::encoding const&)'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::textPartFactory::getInstance()'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::stringContentHandler::stringContentHandler(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, vmime::encoding const&)'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::streamContentHandler::isEmpty() const'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::text::text(vmime::text const&)'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vmime::utility::CRLFToLFFilteredOutputStream::CRLFToLFFilteredOutputStream(vmime::utility::outputStream&)'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `vtable for vmime::utility::dotFilteredInputStream'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `typeinfo for vmime::text'
/usr/bin/ld: /usr/local/lib/libvmime.so: undefined reference to `typeinfo for vmime::utility::filteredInputStream'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:3324: tests/bdump] Error 1
make[1]: Leaving directory '/root/gromox-2.10'
make: *** [Makefile:2156: all] Error 2

**Comment by jengelh** [comment]
Not sure. Perhaps an incomplete build from the first run (with the old vmime) that you need to `make clean` so it all can rebuild with the current vmime?

**Comment by jengelh** [comment]
configure-time check added gromox-2.10-94-ged209afe7 .
