### ISSUE TITLE
A slight change to gromox/mra /midb_agent.cpp

### ISSUE THREAD

**Issue by kbekus** [grommunio/gromox#66]
hi there,

sorry I don't know how to use Git properly yet but I've found a slight error in the above file. I was having an issue with a large inbox over IMAP, the error I was receiving was:
[2023-08-03 23:45:52.898810]: E-2154: midb response is longer than expected (262144), rejecting IMAP command. Consider raising midb_command_buffer_size or having fewer mails in the folder.

Tried to Google this error but had no luck. Dug through the source code and found on line 176 the code that pulls that parameter from /etc/gromox/midb_agent.cfg or defaults to 256K if not set.  However the actual parameter needs to be midb_agent_command_buffer_size, not midb_command_buffer_size.

Would you mind changing line 494 so that the printed error message matches the actual parameter name please?

**Comment by jengelh** [comment]
689ac8e182955653d1d0fc73962f2f8b576ed359
