### ISSUE TITLE
Compiler error with current git ed6e0cf

### ISSUE THREAD

**Issue by mniehren** [grommunio/gromox#67]
I got the following compiler error with actual git 

  CXX      mra/pop3/main.o
exch/midb/mail_engine.cpp: In Funktion »void* midbme_scanwork(void*)«:
exch/midb/mail_engine.cpp:2235:22: Fehler: »cmp_greater« ist kein Element von »std«
                 std::cmp_greater(last_diff, g_midb_cache_interval) ||
                     
exch/midb/mail_engine.cpp:2235:22: Anmerkung: empfohlene Alternative: »greater«
                 std::cmp_greater(last_diff, g_midb_cache_interval) ||        
                      greater
exch/midb/mail_engine.cpp:2236:22: Fehler: »cmp_greater« ist kein Element von »std«
                 std::cmp_greater(load_diff, g_midb_reload_interval));
exch/midb/mail_engine.cpp:2236:22: Anmerkung: empfohlene Alternative: »greater«
                 std::cmp_greater(load_diff, g_midb_reload_interval));
                      greater
  CXX      mra/pop3/pop3_cmd_handler.o

**Comment by jengelh** [comment]
f01e3c6a6
