### ISSUE TITLE
Configuring MAPI over HTTPS fails when password contains accent character

### ISSUE THREAD

**Issue by deajan** [grommunio/gromox#69]
I've had a rough time trying to figure out why my Outlook wouldn't want to configure my MAPI profile.
After having changed like any parameter, I found out that using character `è` in my password failed.
`gromox-dscli` utility didn't complain though.

Once I changed the `è` by an `e`, everything started to work like a charm.

I've tried the following chars which work: `$!^#` so it just seems that gromox doesn't like accents.

To confirm my diag, I've tried with `é` char, same thing happens.

Best regards.

Env:
Windows 10 22H2 x64 with Outlook 2019 x64

**Comment by jengelh** [comment]
Known Outlook limitation. https://docs.grommunio.com/kb/auth.html

**Comment by deajan** [comment]
Lol... sorry for the noise then.
