### ISSUE TITLE
Single User Import

### ISSUE THREAD

**Issue by mb1811** [grommunio/gromox#70]
Hi! 
Would it be possible to add a string like

[string ]$SingleMboxes = 'my@mail.xx'

to the exchange2grommunio.ps1 script?

With that Option, it would be possible to a) test the import with a single user and b) run multiple scripts with batches of maybe 5 mailboxes to speed things up.

The actual version of that script does all mailboxes - some exclusions. Which is quite hard to manage for a couple 100 mailboxes.

Tanks!
Matthias

**Comment by WalterHof** [comment]
Added $ImportMboxes, so we may import al list of mailboxes.

# Import only these mailboxes, an array of mail addresses, $IgnoreMboxes will be honored
# To import all mailboxes leave empty, to import only some mailboxes, populate $ImportMboxes
#[string] $ImportMboxes = 'testi1@example.com','testi2@example.com'
[string] $ImportMboxes = ''

Jan please commit.
Walter

**Comment by jengelh** [comment]
gromox-2.14-23-g1f27e29b5
