### ISSUE TITLE
Exchange Export Script

### ISSUE THREAD

**Issue by mb1811** [grommunio/gromox#71]
Thanks for adding the single Import settings! They work fine.

I just made little changes to avoid different writing (upper / lowercase) between the $ImportMboxes/$IgnoreMboxes values and those coming from the Exchange $Mailbox

376 $ImportMboxes = $ImportMboxes.trim()**.ToLower()**
377 $IgnoreMboxes = $IgnoreMboxes.trim()**.ToLower()**
419 $MigMBox = $Mailbox.PrimarySmtpAddress.ToString()**.ToLower()**

**Comment by jengelh** [comment]
https://devblogs.microsoft.com/scripting/using-the-powershell-contains-operator/ suggests .Contains is already impervious to casing.

cc @WalterHof

**Comment by jengelh** [comment]
@WalterHof If we want to be case-preserving, we need to do this differently. (something with `ccontains`?)

**Comment by WalterHof** [comment]
I prefer a construct like this:
if ($ImportMboxes.ToLower().contains($MigMBox.ToLower())) {
this is easier to implement.
Your opinion?

**Comment by jengelh** [comment]
I can't test PS, but if it does what is advertised, sure.

**Comment by jengelh** [comment]
gromox-2.15-37-gd36a98ff7
