### ISSUE TITLE
Bug on upgrade to the latest git 019df99

### ISSUE THREAD

**Issue by mniehren** [grommunio/gromox#72]
That's in the log of http

2023-10-13_22:08:41.35109 dbop: Current database schema: gx-126
2023-10-13_22:08:41.35111 dbop: Upgrading schema to GX-127
2023-10-13_22:08:41.35636 dbop: "ALTER TABLE `associations` ADD PRIMARY KEY (`list_id`,`username`)": Incorrect index name 'list_id_2'

**Comment by jengelh** [comment]
I cannot find a problem with the table upgrade code. Consider e.g.:
```
# echo 'drop database emtest' | mysql
mysql: Deprecated program name. It will be removed in a future release, use '/usr/bin/mariadb' instead
# echo 'create database emtest' | mysql
mysql: Deprecated program name. It will be removed in a future release, use '/usr/bin/mariadb' instead
# cat emtest.cfg 
schema_upgrades=host:f3.lh
mysql_dbname=emtest
mysql_username=root
mysql_password=
# gromox-dbop -c emtest.cfg --create-old
dbop: Creating aliases
dbop: Creating associations
dbop: Creating classes
dbop: Creating domains
dbop: Creating forwards
dbop: Creating groups
dbop: Creating hierarchy
dbop: Creating members
dbop: Creating orgs
dbop: Creating specifieds
dbop: Creating users
dbop: Creating mlists
# gromox-dbop -c emtest.cfg -U
dbop: Current database schema: gx-0
dbop: Upgrading schema to GX-1
dbop: Upgrading schema to GX-2
...
dbop: Upgrading schema to GX-128
```
So the table schemas on your end must have somehow gotten messed up by some external utility.

What is the output of the `show create table associations` SQL command in your case?

**Comment by mniehren** [comment]
if i reproduce your steps, i got an error on upgrade to GX-127:
dbop: Upgrading schema to GX-123
dbop: Upgrading schema to GX-124
dbop: Upgrading schema to GX-125
dbop: Upgrading schema to GX-126
dbop: Upgrading schema to GX-127
dbop: "ALTER TABLE `associations` ADD PRIMARY KEY (`list_id`,`username`)": Incorrect index name 'list_id_2'

Could the cause be my mysql version ?
tuxgromm-test@~# mysql --version
mysql  Ver 15.1 Distrib 10.4.22-MariaDB, for Linux (x86_64) using readline 5.1

and here is the output of the show command in the emtest database:
associations | CREATE TABLE `associations` (
  `list_id` int(10) NOT NULL,
  `username` varchar(320) CHARACTER SET ascii NOT NULL,
  UNIQUE KEY `list_id_2` (`list_id`,`username`)

**Comment by mniehren** [comment]
Update to V10.6.15 resolve's the error,

many thanks Jan
