### ISSUE TITLE
Imported contacts not shown on select list on creating an new mail

### ISSUE THREAD

**Issue by mniehren** [grommunio/gromox#79]
if you import an contact in vcf-format with gromox-vcf2mt it will not shown
on the selected contact list if creating an new mail in Webapp.
It is shown under contacts.

The same problem appears on importing from kopano with
gromox-kdb2mt ... | gromox-mt2exm -u <username>

It is reproducable with the following steps:
- Create an new contact in the Webapp (only Name and Email is enough), everything work's as expected, It is also shown in the new mail dialog
- Export that contact into an vcf-file over the right mouse button
- Delete the contact
- Reimport the vcf-file over Webapp in contacts or gromox-vcf2mt 
- The contact is shown in the contact list but not in the  selected contact list if creating an new mail

**Comment by deajan** [comment]
More descriptions of the issue found at:
https://community.grommunio.com/d/1337-imported-vcards-arent-indexed-in-grommunio-web/4
https://community.grommunio.com/d/1300-kontakt-auswahl-bei-neuer-mail-unvollstandig/21

**Comment by jengelh** [comment]
gromox-2.30-24-gfe6a029d5

**Comment by deajan** [comment]
THANK YOU !!!
