### ISSUE TITLE
ews: cu_send_mail: no SMTP target given

### ISSUE THREAD

**Issue by amaccuish** [grommunio/gromox#82]
`Jan 03 19:57:27 mx01 http[14517]: cu_send_mail: no SMTP target given
Jan 03 19:57:27 mx01 http[14517]: [ews#1] Error: E-3117: failed to send mail (262659)
`

i+ | gromox             | package    | 2.20.121.gf174912-lp155.30.1 | x86_64 | grommunio

outgoing_smtp_url is defined in gromox.cfg and additionally, smtp_server_ip/host in exmdb_provider.cfg for diagnosing, didn't fix the issue.

**Comment by jengelh** [comment]
I believe this to be fixed with gromox-2.20-134-ga4c1450d9 .
