### ISSUE TITLE
typo: mkmidb(8gx)->midb(8gx)

### ISSUE THREAD

**Issue by crpb** [grommunio/gromox#84]
I'm wondering if that should say 'midb(8gx)' as in the service tinkering with those midb.sqlite's (`lsof -p $(pgrep **midb)`)?

https://github.com/grommunio/gromox/blob/804c9c21fc5f9b541ebd82ecfdc9a8241618b7fc/doc/gromox-mkmidb.8#L12-L16

**Comment by jengelh** [comment]
32e724282955db40587be3dc5be6fad0792824c6
