### ISSUE TITLE
gromox-delivery fails

### ISSUE THREAD

**Issue by crpb** [grommunio/gromox#85]
version affected: gromox-2.27.84.g3c69d18-lp155.27.1.x86_64
w/o a config setting in gromox.cfg:outgoing_smtp_url=smtp://localhost the service gromox-delivery fails to start.
```
delivery[28531]: Malformed URL: outgoing_smtp_url="": Malformed URL: No protocol separator.
```

**Comment by jengelh** [comment]
gromox-2.27-85-g[cac61b3e7](https://github.com/grommunio/gromox/commit/cac61b3e759d6fa2c1a609190eb151c4aeddc0b0)
