### ISSUE TITLE
Incorrect EWS serialization

### ISSUE THREAD

**Issue by pavel-faltynek** [grommunio/gromox#86]
Is it possible that the `XMLDUMPM`/`XMLDUMPT` macros don't work as expected for the empty vectors (or similar corner cases)? It looks like there are subsequent not-closed elements in the `mGetStreamingEventsResponseMessage::serialize()` emitted, so the EWS client receives e.g.:

```
...
<Notifications>
<ErrorSubscriptionIds>
...
```
XML data, which is considered as invalid. Unfortunately I'm already almost unable to read the C++ code (especially the `toXMLNode` template) 😁, also as to perform any debugging. Feel free to check/test it.

**Comment by juliaschroeder** [comment]
I tried to reproduce the issue, but all tags are closed properly.  
The generation of invalid XML in the EWS code is highly unlikely. `XMLDUMPT`/`XMLDUMPM` (and subsequently `toXMLNode`) do not generate the XML data directly, but build a tree of `tinyxml2::XMLElement`s, which is then transformed into the final text by the `tinyxml2` library.

If you are sure that this issue exist, please provide the full request and response and system information (distribution, package versions) so we can try to reproduce this.
