### ISSUE TITLE
gromox-mbop delete empty folders

### ISSUE THREAD

**Issue by crpb** [grommunio/gromox#89]
Hi,

i was wondering how i could delete empty subfolders with gromox-mbop.

The use-case would be to empty the trashbin BUT with a timespec which isn't supported.
```
# gromox-mbop -u me@example.com emptyfld -t 2week --soft DELETED --nuke-folders
Combining -t and --nuke-folders is not supported; use two separate mbop calls.
```
Sure, i could just go ahead and do an `.. emptyfld --nuke-folders DELETED` to get rid of all the folders but that would also delete everything from e.g. today which in some cases i don't want/allowed to do.

I guess nuke-folders can't use the timespec as folders don't have a date value or whatever :thinking: ?

Maybe you could add a new feature which only deletes folders that are empty to get around that?

And a dry-run switch would also be nice  :-).

Cheers!

**Comment by jengelh** [comment]
>I guess nuke-folders can't use the timespec as folders don't have a date value or whatever

They have timestamps, but, just like directories in on-disk filesystems, that information does not reflect changes to objects more than one level away. `find /home -type d -mtime 1 -delete` is just as dangerous as --nuke+-t would be: /home does not change time if you create /home/foo/Downloads/some.pdf.

Tersely speaking, --nuke is an atomic operation as far as Gromox is concerned, and so precludes a (meaningful and efficient) dry-run mode. Think of it like `btrfs sub del ...` or SQL's "ON CASCADE DELETE".

**Comment by jengelh** [comment]
gromox-2.30-9-g273af1004
