### ISSUE TITLE
gromox/{imap,pop3} don't support configuration of DH parameters

### ISSUE THREAD

**Issue by robert-scheck** [grommunio/gromox#91]
As of writing, `gromox/{imap,pop3}` don't seem to support configuration of DH parameters. What is missing equals actually NGINX setting `ssl_dhparam` to configure DH parameters according to [RFC 7919](https://www.rfc-editor.org/rfc/rfc7919.html). Any chance to have this in the future?

IIRC Zarafa (and later Kopano Core as a fork) supported this (in a similar way) due to https://github.com/robert-scheck/zarafa-patches/blob/main/zarafa-7.1.13-ssl_dhe.patch, however nowadays I would strongly prefer RFC 7919 using own `dhparam.pem` file instead.

[Technical Guideline TR-02102-2: Cryptographic Mechanisms: Recommendations and Key Lengths](https://www.bsi.bund.de/SharedDocs/Downloads/EN/BSI/Publications/TechGuidelines/TG02102/BSI-TR-02102-2.html) from the German Federal Office for Information Security ("BSI") recommends Perfect Forward Secrecy (PFS), which unfortunately can currently not be fully configured in `gromox/{imap,pop3}` due to missing DHE support (for RSA).

**Comment by jengelh** [comment]
I am not sure that anything needs to be done.

```
# ./http &
gromox-http 2.30 (pid 10556 uid 0)
# openssl s_client -no_tls1_3 -connect localhost:https
subject=CN = a4.inai.de
issuer=C = US, O = Let's Encrypt, CN = E5
---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: ECDSA
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 2446 bytes and written 301 bytes
Verification: OK
---
New, TLSv1.2, Cipher is ECDHE-ECDSA-AES256-GCM-SHA384
Server public key is 256 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-ECDSA-AES256-GCM-SHA384
...

subject=CN = a4.inai.de
issuer=C = US, O = Let's Encrypt, CN = E5
---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: ECDSA
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 2378 bytes and written 393 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 256 bit
This TLS version forbids renegotiation.
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
```
With TLS1.2, I am already getting ECDHE out-of-the-box, and what happens in case of TLS1.3 I do not know (but TLS1.3 is kinda different anyway).

**Comment by robert-scheck** [comment]
I raised this case for non-EC-based DHE with TLSv1.2 (because ECDHE with TLSv1.3 actually works), e.g. specifically:

- DHE-RSA-AES256-GCM-SHA384
- DHE-RSA-CHACHA20-POLY1305
- DHE-RSA-AES128-GCM-SHA256

The cipher suites above are still part of the Mozilla intermediate configuration, when ECDSA-based certificates are not available. Most obvious example clients that benefit from above mentioned cipher suites (there are more niches, not every project likes EC):

- [Windows 8.1](https://www.ssllabs.com/ssltest/viewClient.html?name=IE&version=11&platform=Win%208.1&key=134)
- [Windows 7](https://www.ssllabs.com/ssltest/viewClient.html?name=IE&version=11&platform=Win%207&key=143)

**Comment by jengelh** [comment]
I don't know how to trigger your non-EC mode. `openssl s_client -cipher 'kEDH:ALL'` still gives me ECDHE instead of DHE-RSA.

**Comment by robert-scheck** [comment]
grommunio:

```
$ openssl s_client -connect localhost:993 -tls1_2 -cipher 'DHE-RSA-AES256-GCM-SHA384' < /dev/null 2>&1 | grep Cipher
New, (NONE), Cipher is (NONE)
    Cipher    : 0000
```

Dovecot, HAProxy:

```
$ openssl s_client -connect localhost:993 -tls1_2 -cipher 'DHE-RSA-AES256-GCM-SHA384' < /dev/null 2>&1 | grep Cipher
New, TLSv1.2, Cipher is DHE-RSA-AES256-GCM-SHA384
    Cipher    : DHE-RSA-AES256-GCM-SHA384
$ 
```

**Comment by jengelh** [comment]
Cool. gromox-2.30-14-gd8f0c296b
