### ISSUE TITLE
PROXY support for gromox/{imap,pop3}

### ISSUE THREAD

**Issue by robert-scheck** [grommunio/gromox#93]
As of writing, `gromox/{imap,pop3}` don't seem to support the [PROXY protocol](https://www.haproxy.org/download/2.9/doc/proxy-protocol.txt) from HAProxy. Having PROXY protocol support would be handy especially for IMAPS and POP3S to achieve high-availability setups with SSL/TLS offloading using HAProxy at the edge, e.g. systems with cluster/floating IP addresses in the DMZ. Postfix already supports this using the [`smtpd_upstream_proxy_protocol`](https://www.postfix.org/postconf.5.html#smtpd_upstream_proxy_protocol) option, which covers the SMTPS (for SMTP submission) part.

**Comment by ychromosome** [comment]
@jengelh 
I did a test with enabled "proxy support", but I did not get it working.

I used these settings:

/etc/gromox/imap.cfg
```
imap_accept_haproxy=2
```
/etc/haproxy/haproxy.cfg
```
server gromox-imap ::1:143 send-proxy-v2
```
Aug 27 22:59:30 mail gromox-imap[64572]: rhost=[::1]:56474 user=test LOGIN phase2 rejected: No such user
```

Can you please assist me to get a working config, or if there is a problem with the implementation take a look at it?

**Comment by ychromosome** [comment]
@jengelh thank you for letting me know!
But when I enable it in gromox.cfg with the line in haproxy.cfg thunderbird does not connect anymore.
Can you please elaborate what would be the correct setup?

**Comment by jengelh** [comment]
TB works for me. use s_client(1) to manually start a TLS and IMAP session.
