### ISSUE TITLE
dnsbl_filter doesn't seem to do anything

### ISSUE THREAD

**Issue by robert-scheck** [grommunio/gromox#94]
As per gromox-2.28.1.256f9d8-1.1, configuring `dnsbl_client=<apikey>.authbl.dq.spamhaus.net` in `/etc/gromox/master.cfg` or `/etc/gromox/imap/master.cfg` doesn't seem to do anything for `gromox-imap.service` (yes, didn't forget to restart the service). To avoid getting maybe tricked by AuthBL itself, I've added `*.authbl.example.net. IN A 127.0.0.20` in my example.net zone (actually it's not "example.net" but at a publicly reachable domain) - and it works as expected with Postfix when testing there. Even with log level 6 for gromox, all I can find related to "dnsbl_filter" in the logs is:

```
May 20 13:33:37 mail imap[116026]: service: unloading libgxs_dnsbl_filter.so
```

When revisiting the implementation in commit 09f71ba0a04c6c63665e3b502e2bac371ce91fcf, I currently don't see what I could have misconfigured (or tested wrongly; tested with both, `openssl s_client -connect <IP>:993` which sends `CAPABILITY`, and also with `mutt` as regular IMAP client).

**Comment by jengelh** [comment]
dnsbl_filter was coded in such a way it looks for a *TXT* record (works like an address lookup, but yields a list of gratuitious error messages to show the user):

```
$ host -t PTR ::ffff:127.0.0.2
Host 2.0.0.0.0.0.f.7.f.f.f.f.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa not found: 3(NXDOMAIN)

$ host -t TXT 2.0.0.0.0.0.f.7.f.f.f.f.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.zen.spamhaus.org
2.0.0.0.0.0.f.7.f.f.f.f.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.zen.spamhaus.org descriptive text "Listed by XBL, see https://check.spamhaus.org/query/ip/::ffff:7f00:2"
2.0.0.0.0.0.f.7.f.f.f.f.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.zen.spamhaus.org descriptive text "Listed by XBL, see https://check.spamhaus.org/query/ip/127.0.0.2"
2.0.0.0.0.0.f.7.f.f.f.f.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.zen.spamhaus.org descriptive text "Listed by SBL, see https://check.spamhaus.org/sbl/query/SBL2"
2.0.0.0.0.0.f.7.f.f.f.f.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.zen.spamhaus.org descriptive text "Listed by PBL, see https://check.spamhaus.org/query/ip/127.0.0.2"
2.0.0.0.0.0.f.7.f.f.f.f.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.zen.spamhaus.org descriptive text "Listed by PBL, see https://check.spamhaus.org/query/ip/::ffff:7f00:2"
-> block

$ host -t TXT 1.0.0.0.0.0.f.7.f.f.f.f.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.zen.spamhaus.org
Host 1.0.0.0.0.0.f.7.f.f.f.f.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.zen.spamhaus.org not found: 3(NXDOMAIN)
-> pass
```

Does the .authbl.dq.spamhaus.net zone support that?

**Comment by jengelh** [comment]
(Even if there are no TXT RRs but some other RR exists, IMO we should get a positive DNS reply—just with 0 RRs—, perform no iterations in the for() loop, and still hit the final `return false;` to indicate "block".)

**Comment by jengelh** [comment]
gromox-2.28-7-gfed690059

**Comment by robert-scheck** [comment]
I am sorry, but when using gromox-2.30.85.4d271dc-2.9, the [RFC 5782](https://www.rfc-editor.org/rfc/rfc5782) [§ 2.1](https://www.rfc-editor.org/rfc/rfc5782#section-2.1) doesn't seem to be followed, because only a TXT lookup ("MAY check the TXT record") happens, but no A lookup ("MUST check the A record"), verified using tcpdump.

**Comment by jengelh** [comment]
gromox-2.32-9-g8f36a69fc
