### ISSUE TITLE
Wrong default permissions of /etc/gromox/ in RPM package

### ISSUE THREAD

**Issue by robert-scheck** [grommunio/gromox#96]
At least gromox-2.28.1.256f9d8-1.1 and gromox-2.28.12.gdf8059d-31.1 lead to the following default permissions for `/etc/gromox/`:

```
$ ls -ld /etc/gromox/
drwxr-xr-x. 2 grommunio gromox 4096 May 21 22:27 /etc/gromox/
$ 
```

As of writing the documentation at [admin/manual_core.rst#permissions](https://github.com/grommunio/grommunio-documentation/blob/master/admin/manual_core.rst#permissions) says however:

> The directory `/etc/gromox` and all contents are supposed to be owned by either user `root` or `grommunio`, be owned by group `gromoxcf` read-only, and be otherwise inaccessible. Gromox has no need to update config files at all, just read them. AAPI needs to write there (which it can via the `grommunio` user ownership). Any other users ought not to be able to access this directory as it contains credentials for MySQL and LDAP.
> 
> ```
> drwxr-x--- 2 grommunio gromoxcf 125 Feb 20 21:47 /etc/gromox
> ```

From my understanding the default permissions of `/etc/gromox/` in RPM package should be corrected to match the documentation on one hand and to provide secure default permissions on the other.

**Comment by jengelh** [comment]
Fixed since 2.28.12.gdf8059d-32.1.
